version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynet
    volumes:
      - mongo_data:/data/db
  mongoexpresspractice:
    image: mongoexpresspractice
    container_name: mongoexpresspractice
    ports:
     - "3000:3000"
    networks:
      - mynet
    volumes:
      - mongoexpress_data:/usr/share/percelkoi/data
    environment:
      - Debug=1
      - MONGODB_HOST=mongo
    depends_on:
      - mongo
networks:
  mynet:
    driver: bridge
volumes:
  mongo_data:
  mongoexpress_data:
